seiyonnet/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.home, name='home'),

    path('search/', views.search, name='search'),
    path('profile/<str:user_username>', views.profile, name='profile'),
    path('profile/<str:user_username>/edit', views.profileedit, name='profileedit'),

    path('anony/', views.anony, name='anony'),
    path('anony_postcreate/', views.anonypostcreate, name='anonypostcreate'),
    path('anony_detail/<int:post_id>', views.anonydetail, name='anonydetail'),
    path('anony_detail/<int:post_id>/edit', views.anonydetail_edit, name='anonydetail_edit'),
    path('anony_detail/<int:post_id>/delete', views.anonydetail_delete, name='anonydetail_delete'),
    path('new_comment/<int:post_id>', views.newcomment, name='newcomment'),
    path('new_comment/<int:post_id>/delete/<int:comment_id>', views.comment_delete, name='comment_delete'),

    path('free/', views.free, name='free'),
    path('free_postcreate/', views.freepostcreate, name='freepostcreate'),
    path('free_detail/<int:post_id>', views.freedetail, name='freedetail'),
    path('free_detail/<int:post_id>/edit', views.freedetail_edit, name='freedetail_edit'),
    path('free_detail/<int:post_id>/delete', views.freedetail_delete, name='freedetail_delete'),
    path('new_freecomment/<int:post_id>', views.newfreecomment, name='newfreecomment'),
    path('new_freecomment/<int:post_id>/delete/<int:comment_id>', views.freecomment_delete, name='freecomment_delete'),

    path('anony_like/<int:post_id>', views.anony_like, name='anony_like'),
    path('free_like/<int:post_id>', views.free_like, name='free_like'),

    path('accounts/login/', accounts_views.login, name='login'),    
    path('accounts/logout/', accounts_views.logout, name='logout'),
    path('accounts/signup/', accounts_views.signup, name='signup'),

    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.conf import settings 
from django.contrib.auth.models import User

#프로필 

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/', blank=True, null=True)
    like_anonyposts = models.ManyToManyField('AnonyPost', blank=True, related_name='like_anonyposts')
    like_freeposts = models.ManyToManyField('FreePost', blank=True, related_name='like_freeposts')

    def __str__(self):
        return self.user.username

#익명게시판

class AnonyPost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, null=True, default='', on_delete=models.CASCADE)
    anony = models.BooleanField(default=True)
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class AnonyComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(AnonyPost, null=True, blank=True, on_delete=models.CASCADE)
    author =  models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE) 

    class Meta:
      ordering = ['-date'] #댓글 최신순

    def __str__(self):
        return self.comment

#자유게시판

class FreePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    author =  models.ForeignKey(User, on_delete=models.CASCADE) 
    anony = models.BooleanField(default=False)
    like_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class FreeComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author =  models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE, related_name='freecomment_author') #익명이 아니므로 저자 있어야함
    post = models.ForeignKey(FreePost, null=True, blank=True, on_delete=models.CASCADE, related_name='freecomment_post')

    def __str__(self):
        return self.comment

board/forms.py
from django import forms
from .models import Profile, AnonyPost, AnonyComment, FreePost, FreeComment

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

#익명게시물 폼
class PostForm(forms.ModelForm):
    class Meta:
        model = AnonyPost
        fields = ['title', 'body', 'image']
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }

        self.fields['body'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20,
            'cols' : 100
        }

#익명댓글 폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = AnonyComment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "댓글을 입력해주세요",
            'rows': 3,
            'cols': 150
        }

#자유게시물 폼
class FreePostForm(forms.ModelForm):
    class Meta:
        model = FreePost
        fields = ['title', 'body', 'image']

    def __init__(self, *args, **kwargs):
        super(FreePostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20
        }

        self.fields['body'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "글 제목을 입력해주세요",
            'rows': 20,
            'cols' : 100
        }

#자유댓글 폼
class FreeCommentForm(forms.ModelForm):
    class Meta:
        model = FreeComment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super(FreeCommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs = {
            'class': 'form-control',
            'placeholder': "댓글을 입력해주세요",
            'rows': 3,
            'cols': 150
        }

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm, FreeCommentForm, FreePostForm,ProfileForm
from .models import Profile,AnonyPost,AnonyComment,FreePost,FreeComment
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.paginator import Paginator
from django.db.models import Max
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'index.html')

def search(request):
    if request.method == 'GET':
        search = request.GET.get('keyword')
        if search:
            posts1 = AnonyPost.objects.filter(
            Q(title__icontains = search) | #제목
            Q(body__icontains = search) #내용
            )      
            posts2 = FreePost.objects.filter(
            Q(title__icontains = search) | #제목
            Q(body__icontains = search) #내용
            )      
            posts = posts1.union(posts2) #검색 결과  합치기 
            return render(request, 'search.html', {'posts':posts})
    return render(request, 'index.html')

def profile(request, user_username):
    user = get_object_or_404(User, username=user_username) 
    userprofile = get_object_or_404(Profile, user_id = user.id) #user id로 프로필 찾기 
    my_anony_posts = AnonyPost.objects.filter(author=user)
    my_free_posts = FreePost.objects.filter(author=user)
    return render(request, 'profile.html', {'userprofile':userprofile, 'my_anony_posts':my_anony_posts, 'my_free_posts':my_free_posts})
    
@login_required
def profileedit(request, user_username):
    user = get_object_or_404(User, username=user_username) 
    userprofile = get_object_or_404(Profile, user_id = user.id) #user id로 프로필 찾기 
    if request.method == 'POST' or request.method == 'FILES':
        form = ProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save()
            return redirect('profile', user_username)
    else:
        form = ProfileForm(instance=userprofile)
    return render(request, 'profile_edit_form.html', {'form':form, 'userprofile':userprofile})

###
# 익명게시판
###

def anony(request):
    posts = AnonyPost.objects.filter().order_by('-date')
    paginator = Paginator(posts, 5)
    pagnum = request.GET.get('page')
    posts = paginator.get_page(pagnum)
    return render(request, 'anony.html', {'posts':posts})

def anonypostcreate(request):
    if request.method == 'POST' or request.method == 'FILES':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.author = request.user  # user 추가!
            unfinished.save()
            form.save()
            return redirect('anony')
    else:
        form = PostForm()
    return render(request, 'anony_post_form.html', {'form':form})

def anonydetail(request, post_id):
    post_detail = get_object_or_404(AnonyPost, pk=post_id)
    comment_form = CommentForm()
    return render(request, 'anony_detail.html', {'post_detail':post_detail, 'comment_form': comment_form})

@login_required
def anonydetail_edit(request, post_id):
    post = get_object_or_404(AnonyPost, pk=post_id)
    if request.method == 'POST' or request.method == 'FILES':
        form = PostForm(request.POST, request.FILES,instance=post)
        if form.is_valid():
            form.save()
            return redirect('anony')
    else:
        form = PostForm(instance=post)
    return render(request, 'anony_post_form.html', {'form':form})

@login_required
def anonydetail_delete(request, post_id):
    delete_post = get_object_or_404(AnonyPost, pk=post_id)
    delete_post.delete()
    return redirect('anony')

@login_required
def newcomment(request, post_id):
    if request.method == 'POST':
        filled_form = CommentForm(request.POST)
        if filled_form.is_valid():
            finished_form = filled_form.save(commit=False)
            finished_form.post = get_object_or_404(AnonyPost, pk=post_id)
            finished_form.author = request.user #댓글 작성자
            finished_form.save()
        return redirect('anonydetail', post_id)

@login_required
def comment_delete(request, post_id, comment_id):
    delete_comment = get_object_or_404(AnonyComment, pk=comment_id)
    delete_comment.delete()
    return redirect('anonydetail', post_id)

@login_required
def anony_like(request, post_id):
    post = get_object_or_404(AnonyPost, id=post_id)
    user = get_object_or_404(User, username=request.user.username) 
    profile = Profile.objects.get(user_id=user.id)
    check_like_post = profile.like_anonyposts.filter(id=post_id)
    if check_like_post.exists():
        profile.like_anonyposts.remove(post)
        post.like_count -= 1
        post.save()
    else:
        profile.like_anonyposts.add(post)
        post.like_count += 1
        post.save()
    return redirect('anonydetail', post_id)

###
# 자유게시판
###

def free(request):
    posts = FreePost.objects.filter().order_by('-date')
    paginator = Paginator(posts, 5)
    pagnum = request.GET.get('page')
    posts = paginator.get_page(pagnum)
    return render(request, 'free.html', {'posts':posts})

@login_required
def freepostcreate(request):
    if request.method == 'POST' or request.method == 'FILES':
        form = FreePostForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.author = request.user  # user 추가!
            unfinished.save()
            return redirect('free')
    else:
        form = FreePostForm()
    return render(request, 'free_post_form.html', {'form':form})

def freedetail(request, post_id):
    post_detail = get_object_or_404(FreePost, pk=post_id)
    comment_form = FreeCommentForm()
    return render(request, 'free_detail.html', {'post_detail':post_detail, 'comment_form': comment_form})

@login_required
def freedetail_edit(request, post_id):
    post = get_object_or_404(FreePost, pk=post_id)
    if request.method == 'POST' or request.method == 'FILES':
        form = PostForm(request.POST, request.FILES,instance=post)
        if form.is_valid():
            form.save()
            return redirect('free')
    else:
        form = PostForm(instance=post)
    return render(request, 'free_post_form.html', {'form':form})

@login_required
def freedetail_delete(request, post_id):
    delete_post = get_object_or_404(FreePost, pk=post_id)
    delete_post.delete()
    return redirect('free')

@login_required
def newfreecomment(request, post_id):
    if request.method == 'POST':
        filled_form = FreeCommentForm(request.POST)
        if filled_form.is_valid():
            finished_form = filled_form.save(commit=False)
            finished_form.post = get_object_or_404(FreePost, pk=post_id)
            finished_form.author = request.user #댓글 작성자
            finished_form.save()
        return redirect('freedetail', post_id)

@login_required
def freecomment_delete(request, post_id, comment_id):
    delete_comment = get_object_or_404(FreeComment, pk=comment_id)
    delete_comment.delete()
    return redirect('freedetail', post_id)

@login_required
def free_like(request, post_id):
    post = get_object_or_404(FreePost, id=post_id)
    user = get_object_or_404(User, username=request.user.username) 
    profile = Profile.objects.get(user_id=user.id)
    check_like_post = profile.like_freeposts.filter(id=post_id)
    if check_like_post.exists():
        profile.like_freeposts.remove(post)
        post.like_count -= 1
        post.save()
    else:
        profile.like_freeposts.add(post)
        post.like_count += 1
        post.save()
    return redirect('freedetail', post_id)

board/templates/anony.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow m-3">
    <div class="card-header py-3 d-flex justify-content-between">
        <h6 class="m-3 font-weight-bold text-success">익명게시판</h6>
        {% if user.is_authenticated %}
        <a href="{% url 'anonypostcreate' %}" class="btn btn-success btn-icon-split m-2 ">
        <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
        </span>
        <span class="text">글쓰기</span>
        </a>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width='70%'>글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'anonydetail' post.id %}">{{ post.title }}</a>
                        {% if post.image %}
                        <i class="fas  fa-image"></i>
                        {% endif %}
                        </td>

                        <td>{{ post.date }}</td>
                        <td>익명</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--페이지네이션-->
<div class="text-center">
    {% if posts.has_previous %}
    <a href= "?page={{posts.previous_page_number}}"> 이전 페이지 </a>
    {% endif %} 

    <span> {{posts.number}} </span> 
    <span> / </span> 
    <span> {{posts.paginator.num_pages}} </span> 

    <br>
    {% if posts.has_next %}
    <a href="?page={{posts.next_page_number}}"> 다음 페이지 </a>
    {% endif %}
</div>

{% endblock %}

board/templates/anony_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card shadow p-5 m-3">
    <h1 class="m-2 mb-4"> {{ post_detail.title }}</h1>
    <small class="text">{{ post_detail.date}}</small>

    <small class="text">익명</small>
    
    <hr/>
    <p class="alert">
        {{ post_detail.body }}
        <br>
        {% if post_detail.image %}
          <img src="{{post_detail.image.url}}" width="300" class="mt-5">
        {% endif %}
    </p>

    {% if user.is_authenticated %}
        {% if user.id == post_detail.author.id %}
            <div class="mt-5">
                <button class="btn btn-outline-primary btn-sm"><a href="{% url 'anonydetail_delete' post_detail.id %}">삭제</a><br/></button>
                <button class="btn btn-outline-primary btn-sm"><a href="{% url 'anonydetail_edit' post_detail.id %}">수정</a></button>
            </div>
        {% endif %}
    {% endif %} 

    <div class="mt-4">
      <a href="{% url 'anony_like' post_detail.id %}"><button type="button" class="btn btn-outline-light">
        {% if post_detail in user.profile.like_anonyposts.all %}
          <i class="fas fa-heart" style="color:red; font-size: 17px;"></i>
        {% else %}
          <i class="far fa-heart" style="color:red; font-size: 17px;"></i>
        {% endif %}
      </button></a>
      <span class="small">
        {% if post_detail in user.profile.like_anonyposts.all %}
          {{ user }} 님 외 {{ post_detail.like_count }}명이 이 게시물을 좋아합니다
        {% else %}
          {{ post_detail.like_count }}명이 이 게시물을 좋아합니다
        {% endif %}
      </span>



    </div><hr/>

    <!-- 댓글 입력 공간 -->
    <form method="POST" action="{% url 'newcomment' post_detail.id  %}">
        {% csrf_token %}
        <div class="d-flex"> 
            <div class="form-group"> {{ comment_form }} </div>
            <input type="submit" class="btn btn-primary btn-sm m-4" value="댓글 입력"/>
        </div>
    </form><br>

    <!-- 댓글 목록 공간 -->
    {% for comment in post_detail.anonycomment_set.all %}
        <div class="d-flex justify-content-between">
            <div>
                <small class="text fw-light mr-3">{{ comment.date }}</small>    
                <span class="fw-bold">{{ comment }}</span>
            </div>

            {% if user.is_authenticated %}
                {% if user.id == comment.author.id %}
                    <a href="{% url 'comment_delete' post_detail.id comment.id %}">❌</a>
                {% endif %}
            {% endif %} 
        </div>

    <hr>
    {% endfor %}

</div>

{% endblock %}

board/templates/anony_post_form.html
{% extends 'base.html' %}
{% block content %}

<div class="card shadow m-3">
    <div class="card-header py-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_p}}
            </table>
            <br/>
            <input type="submit" class="btn btn-success " value="create">
        </form>
    </div>
</div>
{% endblock %}

board/templates/free.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow m-3">
    <div class="card-header py-3 d-flex justify-content-between">
        <h6 class="m-3 font-weight-bold text-success">자유게시판</h6>
        {% if user.is_authenticated %}
        <a href="{% url 'freepostcreate' %}" class="btn btn-success btn-icon-split m-2 ">
        <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
        </span>
        <span class="text">글쓰기</span>
        </a>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width='70%'>글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'freedetail' post.id %}">{{ post.title }}</a>
                        {% if post.image %}
                        <i class="fas  fa-image"></i>
                        {% endif %}
                        </td>
                        <td>{{ post.date }}</td>
                        <td>{{ post.author.username }} </td> <!--작성자-->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--페이지네이션-->
<div class="text-center">
    {% if posts.has_previous %}
    <a href= "?page={{posts.previous_page_number}}"> 이전 페이지 </a>
    {% endif %} 

    <span> {{posts.number}} </span> 
    <span> / </span> 
    <span> {{posts.paginator.num_pages}} </span> 

    {% if posts.has_next %}
    <a href="?page={{posts.next_page_number}}"> 다음 페이지 </a>
    {% endif %}
</div>

{% endblock %}

board/templates/free_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="card shadow p-5 m-3">
    <h1 class="m-2 mb-4"> {{ post_detail.title }}</h1>
    <small class="text">{{ post_detail.date}}</small>
    <small class="text">{{ post_detail.author.username}}</small>
    
    <hr/>
    <p class="alert">
        {{ post_detail.body }}<br>
        {% if post_detail.image %}
          <img src="{{post_detail.image.url}}" width="300" class="mt-5">
        {% endif %}
    </p>

    {% if user.is_authenticated %}
        {% if user.id == post_detail.author.id %}
            <div class="mt-5">
                <button class="btn btn-outline-primary btn-sm"><a href="{% url 'freedetail_delete' post_detail.id %}">삭제</a><br/></button>
                <button class="btn btn-outline-primary btn-sm"><a href="{% url 'freedetail_edit' post_detail.id %}">수정</a></button>
            </div>
        {% endif %}
    {% endif %} 

    <div class="mt-4">
      <a href="{% url 'free_like' post_detail.id %}"><button type="button" class="btn btn-outline-light">
        {% if post_detail in user.profile.like_freeposts.all %}
          <i class="fas fa-heart" style="color:red; font-size: 17px;"></i>
        {% else %}
          <i class="far fa-heart" style="color:red; font-size: 17px;"></i>
        {% endif %}
      </button></a>
      <span class="small">
        {% if post_detail in user.profile.like_freeposts.all %}
          {{ user }} 님 외 {{ post_detail.like_count }}명이 이 게시물을 좋아합니다
        {% else %}
          {{ post_detail.like_count }}명이 이 게시물을 좋아합니다
        {% endif %}
      </span>

    <!-- 댓글 입력 공간 -->
    <form method="POST" action="{% url 'newfreecomment' post_detail.id  %}">
        {% csrf_token %}
        <div class="d-flex"> 
            <div class="form-group"> {{ comment_form }} </div>
            <input type="submit" class="btn btn-primary btn-sm m-4" value="댓글 입력"/>
        </div>
    </form><br>

    <!-- 댓글 목록 공간 --> <!--related_name있으므로 set이 아니라 related_name인 freecomment_post 으로 접근-->
    {% for comment in post_detail.freecomment_post.all %}
        <div class="d-flex justify-content-between">
            <div>
                <small class="text fw-light mr-3">{{ comment.date }}</small>    
                <small class="text fw-light mr-3">{{ comment.author.username }}</small>    
                <span class="fw-bold">{{ comment }}</span>
            </div>

            {% if user.is_authenticated %}
                {% if user.id == comment.author.id %}
                    <a href="{% url 'freecomment_delete' post_detail.id comment.id %}">❌</a>
                {% endif %}
            {% endif %} 
        </div>

    <hr>
    {% endfor %}

</div>

{% endblock %}

board/templates/free_index.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-success">자유게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width='70%'>글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in freeposts %}
                    <tr>
                        <td><a href="{% url 'freedetail' post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.date }}</td>
                        <td>{{ post.author.username }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<a href="{% url 'freepostcreate' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-flag"></i>
    </span>
    <span class="text">글쓰기</span>
</a>
{% endif %}
{% endblock %}

board/templates/free_post_form.html
{% extends 'base.html' %}
{% block content %}

<div class="card shadow m-3">
    <div class="card-header py-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_p}}
            </table>
            <br/>
            <input type="submit" class="btn btn-success" value="create">
        </form>
    </div>
</div>
{% endblock %}

board/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="shadow m-5">
  <div class="p-5 text-center">

      {% if userprofile.image %}
        <img class="img-profile rounded-circle shadow animated--grow-in m-5" width="100" src="{{ userprofile.image.url }}"/>
      {% else %}
        <img class="img-profile rounded-circle shadow animated--grow-in m-5" width="100" src="{% static 'img/undraw_profile.svg' %}"/>
      {% endif %}

      <div class="text-lg">{{userprofile.user.username}} 님의 프로필
      </div>
      <div>{{userprofile.user.email}}</div><br>

      {% if user.is_authenticated %}
        {% if user.id == userprofile.user.id %}
          <div><a href="{%url 'profileedit' user.username%}">프로필 수정하기&RightArrow;</a></div>
        {% endif %}
      {% endif %}

      <div>
        <div class="card shadow m-5 p-4"> 내가 쓴 익명게시글 <hr>
        {% for mypost in my_anony_posts.all %}
          <a href="{%url 'anonydetail' mypost.id%}" class="m-2">{{mypost}}</a>
        {% endfor %}
        </div>
        <div class="card shadow m-5 p-4"> 내가 쓴 자유게시글 <hr>
        {% for mypost in my_free_posts.all  %}
          <a href="{%url 'freedetail' mypost.id%}" class="m-2">{{mypost}}</a>
        {% endfor %}
        </div>
        <div class="card shadow m-5 p-4"> 내가 좋아요 한 익명게시글 <hr>
        {% for likepost in userprofile.like_anonyposts.all %}
          <a href="{%url 'anonydetail' likepost.id%}" class="m-2">{{likepost}}</a>
        {% endfor %}
        </div>
        <div class="card shadow m-5 p-4"> 내가 좋아요 한 자유게시글 <hr>
        {% for likepost in userprofile.like_freeposts.all %}
          <a href="{%url 'anonydetail' likepost.id%}" class="m-2">{{likepost}}</a>
        {% endfor %}
        </div>
      </div>
</div>
</div>

{% endblock %}

board/templates/profile_edit_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1 class="m-5">프로필 수정하기</h1>
<div class="card text-center m-5">
    <div class="card-header" width="100px">

      {% if userprofile.image %}
        <img class="img-profile rounded-circle shadow animated--grow-in m-5" width="100" src="{{ userprofile.image.url }}"/>
      {% else %}
        <img class="img-profile rounded-circle shadow animated--grow-in m-5" width="100" src="{% static 'img/undraw_profile.svg' %}"/>
      {% endif %}

        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{form.as_p}}
            </table>
            <br/>
            <input type="submit" class="btn btn-success mb-4" value="create">
        </form>
    </div>
</div>
{% endblock %}

board/templates/search.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Heading -->
<!-- DataTales Example -->
<div class="card shadow m-3">
    <div class="card-header py-3">
        <h6 class="m-3 font-weight-bold text-success">자유게시판</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th width='70%'>글 제목</th>
                        <th>작성 날짜</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    {% if post.anony %}
                    <tr>
                        <td><a href="{% url 'anonydetail' post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.date }}</td>
                        <td>익명</td>
                    </tr>
                    {% else %}
                    <tr>
                        <td><a href="{% url 'freedetail' post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.date }}</td>
                        <td>{{ post.author.username }} </td> <!--작성자-->
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}